config/routes.rb
Rails.application.routes.draw do
  resources :links
  resources :homepage, only: :index
  resources :sessions, only: :new
  resource :sessions, only: :destroy, as: :session
  get 'sessions/add_account', to: 'sessions#edit', as: :add_account
  post 'sessions/update_active_team', to: 'sessions#update', as: :update_active_team

  #Slack API redirects
  get 'sessions/create', to: 'sessions#create'
  get 'registration/' => 'registration#register', as: :register
  get 'sessions/link', to: 'sessions#link', as: :link_account

  root to: 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/error_collection.rb
module ErrorCollection
  def collect_errors_from(*objects)

    objects.each do |object|
      object.errors.messages.each do |attribute, errors|
        errors.each do |error|
          self.errors.add("#{underscored_klass}_#{attribute.to_s}",
                          error)
        end
      end
    end
  end

  private

  def underscored_klass
    self.class.to_s.underscore
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user_from, class_name: 'SlackAccount'
  belongs_to :team
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :tagged_users, class_name: 'SlackAccount', join_table: 'user_tags'
  belongs_to :metadata

  delegate :title, to: :metadata, allow_nil: true
  delegate :domain, to: :metadata, allow_nil: true
  delegate :description, to: :metadata, allow_nil: true

  validates :url, :user_from, presence: true
end

app/models/metadata.rb
class Metadata < ActiveRecord::Base
  has_attached_file :image
  has_many :links

  validates_attachment :image, content_type: { content_type: /^image\/(png|gif|jpeg)/ }
end

app/models/slack_account.rb
class SlackAccount < ActiveRecord::Base
  has_many :links
  belongs_to :user
  belongs_to :team
  has_and_belongs_to_many :tagged_links, class_name: 'Link', join_table: 'user_tags'

  validates :slack_id, uniqueness: :team

  def self.slack_find(slack_user_id, team_id)
    where(slack_id: slack_user_id, team_id: team_id).first
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :slack_account
  belongs_to :team
  has_and_belongs_to_many :links

  validates :name, presence: true, uniqueness: :team
end

app/models/team.rb
class Team < ApplicationRecord::Base
  has_and_belongs_to_many :slack_accounts
  has_many :tags
  has_many :links
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tags
  belongs_to :active_team, class_name: 'Team'
  has_many :slack_accounts
  has_many :teams, through: :slack_accounts

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/models/user_tag.rb
class UserTag < ActiveRecord::Base
  belongs_to :link
  belongs_to :slack_account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  include Pundit

  protect_from_forgery with: :exception

  def authenticate_user
    redirect_to new_session_path unless current_user.present?
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    if current_user
      redirect_to links_path
    else
      render :index
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user
  before_action :load_and_authorize_link, only: [:show, :destroy]

  def index
    @links = policy_scope(Link)
    @user_teams = current_user.teams
  end

  def show
    redirect_to @link.url
  end

  def destroy
    if @link.destroy
      redirect_to links_path, notice: 'Link deleted'
    else
      redirect_to links_path, error: 'There was a problem deleting the link'
    end
  end

  private

  def load_and_authorize_link
    @link = Link.find(params[:id])
    authorize @link

  rescue Pundit::NotAuthorizedError
    redirect_to links_path
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def register
    TeamRegistrar.perform(params[:code], current_user)
    flash[:notice] = 'Team registered successfully!'
    redirect_to new_session_path,
                notice: 'Team Registered! Welcome to LinkBot!<br />Please sign in with your Slack account to see your links'.html_safe


  rescue Slack::Web::Api::Error => error
    if error.message.include?('already registered') && current_user
      redirect_to links_path,
                  notice: "You've already registered that team! Here are your links!"

    elsif error.message.include?('already registered') && !current_user
      redirect_to new_session_path,
                  notice: "You've already registered that team! Sign in to see your links!"

    else
      redirect_to homepage_index_path, notice: error.message.humanize
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    get_user_auth_response(sessions_create_url)
    load_and_verify_user if user_team.present?

    if user_team.nil?
      redirect_to root_path, notice: 'You must add LinkBoy to your team before signing in!'
    elsif sign_in( @user || create_user )
      redirect_to links_path, notice: "Hi, #{current_user.first_name}!"
    else
      redirect_to root_path, notice: 'Whoops! There was a problem signing you in!'
    end
  end

  def link
    get_user_auth_response(link_account_url)

    existing_slack_account = SlackAccount.slack_find(user_attributes['id'], user_team.id)

    if user_team.nil?
      redirect_to root_path, notice: 'You must add LinkBoy to your team before signing in with that account!'
    elsif existing_slack_account.present? && existing_slack_account.user == current_user
      current_user.update(active_team: existing_slack_account.team)
      redirect_to links_path, notice: 'You\'ve already linked that account, here are your links.'
    elsif existing_slack_account.present? && existing_slack_account.user != current_user
      existing_slack_account.update(user: current_user)
      current_user.update(active_team: existing_slack_account.team)
      redirect_to links_path, notice: 'Account linked! Here\'s your team\'s dashboard.'
    elsif existing_slack_account.blank?
      new_account = SlackAccount.create(
          user: current_user,
          team: user_team,
          slack_id: user_attributes['id'],
          email: user_attributes['email']
      )
      current_user.update(active_team: new_account.team)
      redirect_to links_path, notice: 'Account linked! Here\'s your team\'s dashboard.'
    else
      redirect_to links_path, notice: 'There was a problem signing in with your account.'
    end
  end

  def update
    team = Team.find(params[:team_id])

    if current_user.update(active_team: team)
      redirect_to links_path
    else
      redirect_to links_path, notice: 'There was a problem switching teams!'
    end
  end

  def destroy
    if sign_out
      redirect_to root_path, notice: 'Successfully signed out!'
    else
      redirect_to root_path, notice: 'Whoops!'
    end
  end

  private

  def load_and_verify_user
    @user = SlackAccountUserQuerier.perform(
        email: user_attributes['email'],
        slack_user_id: user_attributes['id'],
        slack_team_id: user_attributes['team_id']
    )
  end

  def get_user_auth_response(redirect_uri)
    slack_client = Slack::Web::Client.new

    @auth_response = slack_client.oauth_access(
        client_id: ENV['SLACK_CLIENT_ID'],
        client_secret: ENV['SLACK_CLIENT_SECRET'],
        code: params[:code],
        redirect_uri: redirect_uri
    )

    slack_client.token = @auth_response['access_token']
    @user_response = slack_client.users_info(user: @auth_response['user']['id'])
  end

  def create_user
    UserCreator.perform(user_attributes['id'], user_attributes['team_id'], user_attributes['email'])
  end

  def user_attributes
    @user_response['user'].merge(@auth_response['user'])
  end

  def user_team
    Team.find_by_team_id(user_attributes['team_id'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_image_path(link)
    if link.metadata.present? && link.metadata.image.present?
      link.metadata.image.expiring_url
    else
      'placeholder.png'
    end
  end

  def link_domain(link)
    link.domain || link.url
  end
end

app/views/homepage/index.html.erb
<div class='welcome'>
  <h1> Welcome to LinkBot!</h1>

  <p class='sign-in-text'>
    If you haven't added LinkBot to your team, click on the 'Add to Slack' button below and we'll get you set up!
  </p>

  <p id='register'>
    <a href="https://slack.com/oauth/authorize?client_id=<%= ENV['SLACK_CLIENT_ID'] %>&scope=bot,channels:read,groups:read,chat:write:bot,users:read">
      <img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" />
    </a>
  </p>

  <p class='sign-in-text'>
    Already have an account?
  </p>

  <p class='sign-in-button'>
    <a href=<%= "https://slack.com/oauth/authorize?scope=identity.basic,identity.email,identity.team&client_id=#{ENV['SLACK_CLIENT_ID']}&redirect_uri=#{sessions_create_url}" %>>
      <img alt="Sign in with Slack" height="40" width="172" src="https://platform.slack-edge.com/img/sign_in_with_slack.png" srcset="https://platform.slack-edge.com/img/sign_in_with_slack.png 1x, https://platform.slack-edge.com/img/sign_in_with_slack@2x.png 2x" />
    </a>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linkbot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/links/index.html.erb
<div class='title-bar'>
  <div class='title'>LinkBoy</div>

  <div class='right-title-group'>
    <% if ENABLE_MULTI_TEAM %>
      <div class='team-select-container'>
        <span>Select team:</span>
        <%= form_tag update_active_team_path, class: 'switch-user-form' do %>
          <%= select_tag('team_id', options_for_select(@user_teams.map { |team| [team.name, team.id]}, current_user.active_team.id) {}, {class: 'team-select'}) %>
        <% end %>
      </div>

      <div class='team-sign-in'>
        <%= link_to 'Add another team', add_account_path %>
      </div>
    <% end %>

    <div class='sign-out-button'><%= link_to 'Sign Out', session_path, method: :delete %></div>
  </div>
</div>

<div class='links-container'>
  <% @links.each do |link| %>
      <div class='link-box-container'>
        <%= link_to link_path(link) do %>
          <div class=link-box>
            <div class='link-image-container'>
              <%= image_tag(link_image_path(link), class: 'link-image') %>
            </div>
            <div class='link-title'>
              <%= link.title %>
            </div>
            <div class='link-domain'>
              <%= link_domain(link) %>
            </div>
              <%= link_to '(Delete)', link_path(link), method: :delete %>
          </div>
        <% end %>
    </div>
<% end %>
</div>